# Data Quality Checks

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
com = pd.read_csv(r'C:\Users\soubh\Downloads\OOPS\Tableau Dashboard\Invisible Dashboard\pipeline\data\Compressed_AQI_Location_Info.csv')

In [4]:
com.head(10)

,date,location_id,sensors_id,location,lat,lon,parameter,units,value,country_name,provider_name,owner_name,is_mobile,is_monitor,instrument_name
0,2024-01-01,8039,23320,Mumbai-8039,19.07283,72.882610,pm25,µg/m³,105.409091,India,AirNow,Unknown Governmental Organization,False,True,Government Monitor
1,2024-01-01,8118,23534,New Delhi-8118,28.63576,77.224450,pm25,µg/m³,213.727273,India,AirNow,Unknown Governmental Organization,False,True,Government Monitor
2,2024-01-01,8172,5077640,Kolkata-931703,22.56263,88.363040,pm25,µg/m³,176.863636,India,StateAir Kolkata,Unknown Governmental Organization,False,True,Government Monitor
3,2024-01-01,8557,24857,Hyderabad-8557,17.38405,78.456360,pm25,µg/m³,94.636364,India,AirNow,Unknown Governmental Organization,False,True,Government Monitor
4,2024-01-01,8558,5077812,Chennai-931708,13.08784,80.278475,pm25,µg/m³,93.090909,India,AirNow,Unknown Governmental Organization,False,True,Government Monitor
5,2024-01-01,3174188,11056907,Malav-3144131,22.70763,75.852570,pressure,hpa,1002.989267,India,Clean Air Catalyst,Clean Air Catalyst,False,True,Serinus 30
6,2024-01-01,3174188,11056908,Malav-3144131,22.70763,75.852570,temperature,c,24.193370,India,Clean Air Catalyst,Clean Air Catalyst,False,True,Serinus 30
7,2024-01-01,3174188,11056910,Malav-3144131,22.70763,75.852570,wind_speed,m/s,1.029891,India,Clean Air Catalyst,Clean Air Catalyst,False,True,Serinus 30
8,2024-01-01,3174188,11056920,Malav-3144131,22.70763,75.852570,wind_direction,deg,127.288350,India,Clean Air Catalyst,Clean Air Catalyst,False,True,Serinus 30
9,2024-01-01,3174188,11056921,Malav-3144133,22.70763,75.852570,pm25,µg/m³,0.112435,India,Clean Air Catalyst,Clean Air Catalyst,False,True,Serinus 30

In [6]:
com['parameter'].unique()

array(['pm25', 'pressure', 'temperature', 'wind_speed', 'wind_direction',
       'co', 'relativehumidity', 'pm1', 'pm10', 'um003', 'no', 'no2',
       'o3', 'so2'], dtype=object)

In [7]:
com.shape

(273491, 15)

In [9]:
com.describe()

        location_id    sensors_id            lat            lon         value
count  2.734910e+05  2.734910e+05  273491.000000  273491.000000  2.734910e+05
mean   1.450358e+06  1.206185e+07      22.272244      78.745138  4.183593e+19
std    1.622836e+06  1.162418e+06       5.522924       4.913816  1.619829e+22
min    1.700000e+01  2.332000e+04       8.514909      70.909168 -2.873663e+23
25%    7.752000e+03  1.223563e+07      19.024390      75.675238  7.027941e+00
50%    2.707280e+05  1.223682e+07      23.016834      77.482000  2.579348e+01
75%    3.409401e+06  1.223795e+07      26.803650      80.699436  4.895687e+01
max    3.409530e+06  1.281512e+07      34.066210      94.636574  6.364936e+24

In [11]:
com.isnull().sum()

date               0
location_id        0
sensors_id         0
location           0
lat                0
lon                0
parameter          0
units              0
value              0
country_name       0
provider_name      0
owner_name         0
is_mobile          0
is_monitor         0
instrument_name    0
dtype: int64

**Data Is Completely Cleaned**